application: zinthedream
version: pinterest
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "7d"

handlers:
  
- url: /js
  static_dir: js

- url: /css
  static_dir: css
- url: /images
  static_dir: images
  
- url: /.*
  script: main.app
libraries:
- name: jinja2
  version: "2.6"
  
builtins:
- remote_api: on
- appstats: on
- admin_redirect: on
